### ISSUE TITLE
Tasks for Rutgers hackathon

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/HyperSupremeStructure-HSC-LSS#21]
- [x] Wiki with cuts/specs/plots (#19)
- [x] Implement standard pdf stacking in cat_sampler.py (#17)
- [x] Understand PIT and test it to obtain calibrated N(z)s (#17)
- [x] Decide tomography scheme (#16)
- [x] Start implementing the 2-pt correlation function estimation (#22) 
- [x] Make full pipeline run and obtain power spectra
- [x] If we get here we're superheroes, in which case we get started with likelihood (#20)
- [ ] N(z) estimates from COSMOS 30-band photometry (#18)

**Comment by adam-broussard** [comment]
I was able to implement PDF stacking for the N(z)'s in cat_sampler.py.  These plots show the similar N(z) distributions after calculating them using point redshifts and the PDFs.

![pdfstack](https://user-images.githubusercontent.com/33520634/46227334-e0112f00-c32c-11e8-8e7f-1a791a455813.png)
![z_mc](https://user-images.githubusercontent.com/33520634/46227335-e0a9c580-c32c-11e8-9465-4f8d908ccbad.png)

**Comment by adam-broussard** [comment]
We ran the pipeline to completion and generated variance-weighted angular power spectrum plots.

![powerspectrum](https://user-images.githubusercontent.com/33520634/46232614-ae549400-c33d-11e8-9326-66d47c16d2e2.png)

**Comment by damonge** [comment]
7/8 tasks done (including "being superheroes"). Not too bad guys!!!
